# Config for calendar bot

import datetime

# General Settings
# set announcement_channel to 0 to disable the announcements.
settings = {
    "Token": "bot_token",
    "Prefix": "c!",
    "announcement_channel": 0
}

# Websites used for thse days:
# https://nationaldaycalendar.com/march/
# There are 2 more that I forgot to credit.

# Holidays
holidays = {
    "January": {
        '1': 'New Year Day',
        '2': 'Science Fiction Day', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "February": {
        '1': 'Change Your Password Day and G.I. Joe Day',
        '2': "Groundhog's Day", 
        '3': 'Doggy Date Night', 
        '4': 'World Cancer Day and National Thank a Mail Carrier Day', 
        '5': 'Disaster Day', 
        '6': 'Lame Duck Day',
        '7': "'e' Day", 
        '8': 'Laugh and Get Rich Day', 
        '9': 'National Pizza Day',
        '10': 'National Flannel Day', 
        '11': "National Don't Cry Over Spilt Milk Day", 
        '12': 'Darwin Day', 
        '13': 'World Radio Day', 
        '14': "Valentine's Day", 
        '15': 'Single Awareness Day', 
        '16': 'National Innovation Day and Kyoto Protocol Day', 
        '17': 'Random Act of Kindness Day', 
        '18': 'National Drink Wine Day', 
        '19': 'National Chocolate Mint Day', 
        '20': 'National Love Your Pet Day', 
        '21': 'International Mother Language Day', 
        '22': 'European Day for Victims of Crime', 
        '23': 'Curling is Cool Day', 
        '24': 'National Trading Card Day', 
        '25': 'Quiet Day', 
        '26': "Carnival Day, and For Pete's Sake Day", 
        '27': 'Pokémon Day', 
        '28': 'National Choclate Soufflé Day', 
        '29': 'Leap Day'
    },
    "March": {
        '1': "National Peanut Butter Lover's Day",
        '2': "International Rescue Cat Day", 
        '3': 'Talk In Third Person Day', 
        '4': "International Game Master's Day", 
        '5': 'Multiple Personality Day', 
        '6': 'National Alamo Day and National Oreo Cookie Day',
        '7': 'National Cereal Day', 
        '8': "International Women's Day", 
        '9': "Panic Day and Get Over It Day",
        '10': 'Mario Day', 
        '11': 'National Johnny Appleseed Day', 
        '12': 'National Plant A Flower Day', 
        '13': 'National K9 Veterans Day', 
        '14': 'Pi Day', 
        '15': 'National Kansas Day', 
        '16': 'Everything You Do Is Right Day', 
        '17': "St. Patrick's Day", 
        '18': 'National Sloppy Joe Day', 
        '19': 'National Chocolate Caramel Day', 
        '20': 'World Flour Day', 
        '21': 'World Down Syndrome Day', 
        '22': 'National Goof Off Day', 
        '23': 'National Near Miss Day', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "April": {
        '1': "April Fool's Day",
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "May": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': 'Cinco De Mayo', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "June": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': ''
    },
    "July": {
        '1': 'Independence Day (Canada)',
        '2': '', 
        '3': '', 
        '4': 'Independence Day (America)', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "August": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "September": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
    },
    "October": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': 'Leif Erikson Day! Hinga Dinga Durgen!',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': 'Halloween'
    },
    "November": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': ''
    },
    "December": {
        '1': '',
        '2': '', 
        '3': '', 
        '4': '', 
        '5': '', 
        '6': '',
        '7': '', 
        '8': '', 
        '9': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': 'Christmas Eve', 
        '25': 'Christmas', 
        '26': 'Boxing Day', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': "New Year's Eve"
    }
}


