# Config for calendar bot

import datetime

# General Settings
settings = {
    "Token": "bot_token_goes_here",
    "Prefix": "c!",
    "announcement_channels": [ # So you can add more than 1 channel to announce in! 
        "0",
        "0"
    ]
}
# Sources
# https://nationaltoday.com/may-holidays/
# https://nationaldaycalendar.com/may/


# Holidays
holidays = {
    "January": {
        '01': 'New Year Day',
        '02': 'Science Fiction Day', 
        '03': '', 
        '04': '', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "February": {
        '01': 'Change Your Password Day and G.I. Joe Day',
        '02': "Groundhog's Day", 
        '03': 'Doggy Date Night', 
        '04': 'World Cancer Day and National Thank a Mail Carrier Day', 
        '05': 'Disaster Day', 
        '06': 'Lame Duck Day',
        '07': "'e' Day", 
        '08': 'Laugh and Get Rich Day', 
        '09': 'National Pizza Day',
        '10': 'National Flannel Day', 
        '11': "National Don't Cry Over Spilt Milk Day", 
        '12': 'Darwin Day', 
        '13': 'World Radio Day', 
        '14': "Valentine's Day", 
        '15': 'Single Awareness Day', 
        '16': 'National Innovation Day and Kyoto Protocol Day', 
        '17': 'Random Act of Kindness Day', 
        '18': 'National Drink Wine Day', 
        '19': 'National Chocolate Mint Day', 
        '20': 'National Love Your Pet Day', 
        '21': 'International Mother Language Day', 
        '22': 'European Day for Victims of Crime', 
        '23': 'Curling is Cool Day', 
        '24': 'National Trading Card Day', 
        '25': 'Quiet Day', 
        '26': "Carnival Day, and For Pete's Sake Day", 
        '27': 'Pokémon Day', 
        '28': 'National Choclate Soufflé Day', 
        '29': 'Leap Day'
    },
    "March": {
        '01': "National Peanut Butter Lover's Day",
        '02': "International Rescue Cat Day", 
        '03': 'Talk In Third Person Day', 
        '04': "International Game Master's Day", 
        '05': 'Multiple Personality Day', 
        '06': 'National Alamo Day and National Oreo Cookie Day',
        '07': 'National Cereal Day', 
        '08': "International Women's Day", 
        '09': "Panic Day and Get Over It Day",
        '10': 'Mario Day', 
        '11': 'National Johnny Appleseed Day', 
        '12': 'National Plant A Flower Day', 
        '13': 'National K9 Veterans Day', 
        '14': 'Pi Day', 
        '15': 'National Kansas Day', 
        '16': 'Everything You Do Is Right Day', 
        '17': "St. Patrick's Day", 
        '18': 'National Sloppy Joe Day', 
        '19': 'National Chocolate Caramel Day', 
        '20': 'World Flour Day', 
        '21': 'World Down Syndrome Day', 
        '22': 'National Goof Off Day', 
        '23': 'National Chia Pet Day', 
        '24': 'National Chocolate Covered Raisin Day', 
        '25': 'National Medal of Honor Day', 
        '26': 'Epilepsy Awareness Day – Purple Day and National Nougat Day', 
        '27': 'National Scribble Day and National Joe Day', 
        '28': 'National Something on a Stick Day', 
        '29': 'National Vietnam War Veterans Day', 
        '30': 'National Pencil Day and National Take a Walk In The Park Day',
        '31': 'National Bunsen Burner Day and National Tater Day'
    },
    "April": {
        '01': "April Fool's Day",
        '02': 'National Peanut Butter and Jelly Day', 
        '03': 'World Party Day', 
        '04': 'National School Librarian Day', 
        '05': 'National Deep Dish Pizza Day', 
        '06': "New Beer's Eve",
        '07': 'National Beer Day', 
        '08': 'National Zoo Lovers Day', 
        '09': 'National Former Prisoner of War Recognition Day and National Winston Churchill Day',
        '10': 'Encourage A Young Writer Day', 
        '11': 'National Barber Shop Quartet Day', 
        '12': 'National For Twelves Day', 
        '13': 'National Thomas Jefferson Day and National Scrabble Day', 
        '14': 'Look Up at The Sky Day and National Reach as High as You Can Day', 
        '15': 'National Take a Wild Guess Day and National Titanic Remembrance Day', 
        '16': 'National Wear Your Pyjamas To Work Day', 
        '17': 'National Haiku Poetry Day', 
        '18': 'National Animal Cracker Day', 
        '19': 'National Hanging Out Day', 
        '20': 'Unofficial Weed Day.', 
        '21': 'National Kindergarten Day', 
        '22': 'National Earth Day', 
        '23': 'National Lost Dogs Awareness Day', 
        '24': 'National Pigs in a Blanket Day', 
        '25': 'National East Meets West Day', 
        '26': 'National Pretzel Day', 
        '27': 'National Tell a Story Day', 
        '28': 'National Superhero Day', 
        '29': 'National Zipper Day', 
        '30': 'National Adopt a Shelter Pet Day and National Bugs Bunny Day',
        '31': 'Congratulations! YOU FOUND A HIDDEN SECRET!'
    },
    "May": {
        '01': 'Law Day',
        '02': 'National Life Insurance Day', 
        '03': 'National Paranormal Day', 
        '04': 'National Star Wars Day', 
        '05': 'Cinco De Mayo', 
        '06': 'National Beverage Day',
        '07': 'World Password Day', 
        '08': 'National Have a Coke Day', 
        '09': 'National Lost Sock Memorial Day',
        '10': 'Whacking Day (The Simpsons)', 
        '11': 'National Twilight Zone Day', 
        '12': '	National Limerick Day', 
        '13': 'National Frog Jumping Day', 
        '14': 'National Dance Like a Chicken Day', 
        '15': 'National Chocolate Chip Day', 
        '16': 'National Sea Monkey Day', 
        '17': 'National Idaho Day', 
        '18': 'National Visit Your Relatives Day', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "June": {
        '01': '',
        '02': '', 
        '03': '', 
        '04': '', 
        '05': 'Ferris Bueller Day', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': ''
    },
    "July": {
        '01': 'Independence Day (Canada)',
        '02': '', 
        '03': '', 
        '04': 'Independence Day (America)', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "August": {
        '01': '',
        '02': '', 
        '03': '', 
        '04': '', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': ''
    },
    "September": {
        '01': '',
        '02': '', 
        '03': '', 
        '04': '', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '010': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
    },
    "October": {
        '01': '',
        '02': '', 
        '03': '', 
        '04': '', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': 'Leif Erikson Day! Hinga Dinga Durgen!',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': 'Halloween'
    },
    "November": {
        '01': '',
        '02': '', 
        '03': '', 
        '04': '', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': '', 
        '25': '', 
        '26': '', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': ''
    },
    "December": {
        '01': '',
        '02': '', 
        '03': '', 
        '04': '', 
        '05': '', 
        '06': '',
        '07': '', 
        '08': '', 
        '09': '',
        '10': '', 
        '11': '', 
        '12': '', 
        '13': '', 
        '14': '', 
        '15': '', 
        '16': '', 
        '17': '', 
        '18': '', 
        '19': '', 
        '20': '', 
        '21': '', 
        '22': '', 
        '23': '', 
        '24': 'Christmas Eve', 
        '25': 'Christmas', 
        '26': 'Boxing Day', 
        '27': '', 
        '28': '', 
        '29': '', 
        '30': '',
        '31': "New Year's Eve"
    }
}



